apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-curator
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: elasticsearch-curator
              image: elasticsearch/curator:5.8.4
              command: ["/bin/sh", "-c"]
              args: ["curator --config /etc/curator/config.yml /etc/curator/action.yml"]
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/curator
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
